### PR TITLE
Added the abi of GIVEACAKE.sol

### PR DESCRIPTION
**Pull request by icebert04**
This ABI is for setting GIVEACAKE as the main contract

### CODE REVIEW

**Comment by giveacake** [comment]
I will go try on this and let you know

**Comment by giveacake** [comment]
Hi Francis,

Error! Invalid constructor arguments provided. Please verify that they are
in ABI-encoded format

I trying to verify via BSCSCAN but it seems problematic.

Thanks

**Comment by giveacake** [comment]
> This ABI is for setting GIVEACAKE as the main contract

I am using Remix, where do i insert this file, and i deploy to BSCSCAN, then i go verified contract.  possible explain more.

**Comment by icebert04** [comment]
Hello @giveacake 

The reason why you need an ABI, is because it defines which functions you can invoke as well as get a guarantee that the function will return data in the format that you are expecting.

Having only the contract address and the EVM bytecode is not enough. ABI act as a bridge between applications and smart contracts.

For starters. can you try updating your Solidity file? 
I checked it a while ago and it is outdated. 
Please update it now... that could help with our deployment.

Let me know once you're done...

**Comment by giveacake** [comment]
> Hello @giveacake
> 
> The reason why you need an ABI, is because it defines which functions you can invoke as well as get a guarantee that the function will return data in the format that you are expecting.
> 
> Having only the contract address and the EVM bytecode is not enough. ABI act as a bridge between applications and smart contracts.
> 
> For starters. can you try updating your Solidity file?
> I checked it a while ago and it is outdated.
> Please update it now... that could help with our deployment.
> 
> Let me know once you're done...

can we discuss on telegram, my tg is robert_fetto, i already merged your abi, but what do i do next?

**Comment by giveacake** [comment]
Can we discuss on telegram, my telegram is robert_fetto

**Comment by icebert04** [comment]
@giveacake 

Adding you now on Telegram..

**Pull request merged**
